[versions]
ksp = "2.0.21-1.0.25"
agp = "8.10.1"
hiltAndroidGradlePlugin = "2.57.2"
kotlin = "2.0.21"
coreKtx = "1.10.1"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
lifecycleRuntimeKtx = "2.8.7"
lifecycleViewmodelCompose = "2.8.7"
activityCompose = "1.8.0"
composeBom = "2024.06.00"
dagger-hilt = "2.57.2"
splash = "1.0.0"
retrofit = "3.0.0"
moshi = "3.0.0"
moshi-kotlin = "1.15.2"
okhttp = "4.9.3"
okhttp-login-interceptor = "4.9.0"
nav_version = "2.9.6"
hilt-navigation = "1.2.0"
timber = "5.0.1"
coil = "2.7.0"
lottie = "4.0.0"
mockk = "1.12.3"
test-coroutines = "1.8.1"
assert-core = "3.25.3"
turbine = "1.1.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "dagger-hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "dagger-hilt" }
splash-api = { module = "androidx.core:core-splashscreen", version.ref = "splash" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
moshi-kotlin = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshi-kotlin" }
moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "moshi" }
moshi-codegen = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshi-kotlin"}
okHttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttplogginginterceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp-login-interceptor" }
androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycleViewmodelCompose" }
navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "nav_version" }
hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hilt-navigation" }
timber-logs = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
coil = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
lottie-animations = { module = "com.airbnb.android:lottie-compose", version.ref = "lottie" }
mockk-testing = { module = "io.mockk:mockk", version.ref = "mockk"}
test-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "test-coroutines"}
test-assert = { module = "org.assertj:assertj-core", version.ref = "assert-core"}
test-turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine"}

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
dagger = { id = "com.google.dagger.hilt.android", version.ref = "hiltAndroidGradlePlugin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
